name: Build, sign, and push container image

on:
  push:
    branches:
      - main

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "vamsi.sapireddy@outlook.com"
          git config --global user.name "vamsi560"
        env:
          CI: true

      - name: azure login
        run: |
          az login --use-device-code

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Validate YAML files with Spectral
        run: |
          docker run --rm -v "$(pwd):/mnt" stoplight/spectral lint /mnt/**/*.yaml --ruleset /mnt/spectral.yml

      - name: SonarQube Maven Scan
        # You may pin to the exact commit or the version.
        # uses: javiertuya/sonarqube-action@aa12013199d71e4d3cf70322d3b8e84598310c55
        uses: javiertuya/sonarqube-action@v1.3.0
        with:
          github-token: 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
          sonar-host-url: https://sonarcloud.io
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar.organization: vamsi560
          sonar.projectKey: vamsi560_App-Orchestartion          
          
      - name: Build the image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/cosign:1 .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/cosign:1     
      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.2.0
        with:
          cosign-release: v2.2.0

      # Archive cosign.pub as an artifact
      - name: Archive cosign.pub
        uses: actions/upload-artifact@v2
        with:
          name: cosign-pub
          path: cosign.pub

      # Sign the image
      - name: Sign the image and get digest
        run: |
          cosign sign --key cosign.key ${{ secrets.ACR_LOGIN_SERVER }}/cosign:1
          cosign triangulate ${{ secrets.ACR_LOGIN_SERVER }}/cosign:1
          cosign verify --key cosign.pub ${{ secrets.ACR_LOGIN_SERVER }}/cosign:abc6 | jq -r .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/cosign:1
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}          
