name: Build, sign, and push container image
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
 
      - name: azure login
        run: |
          az login --use-device-code
 
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
 
      # Build the image
      - run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/cosign:abc3 .
 
      # Push the image to Azure Container Registry
      - run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/cosign:abc3
      
      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.2.0  
        with:
          cosign-release: v2.2.0  

      # Sign the image
      - run: cosign sign --key cosign.key --notary Rekon:https://rekor.sigstore.dev --yes ${{ secrets.ACR_LOGIN_SERVER }}/cosign:abc3
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
