name: Build, sign, and push container image

on:
  push:
    branches:
      - main

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "vamsi.sapireddy@outlook.com"
          git config --global user.name "vamsi560"
        env:
          CI: true
          
      - name: azure login
        run: |
          az login --use-device-code
 
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build the image
        run: |
          docker build -t vamsisss/cosign:signed .
          docker push vamsisss/cosign:signed
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.2.0
        with:
          cosign-release: v2.2.0

      - name: Sign the image
        run: |
          cosign sign --key cosign.key --yes vamsisss/cosign:signed
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Pull the signed image
        run: |
          docker pull vamsisss/cosign:abc6
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push the signed image to ACR
        run: |
          docker tag vamsisss/cosign:abc6 "${{ secrets.ACR_LOGIN_SERVER }}/cosign:signed"
          docker push "${{ secrets.ACR_LOGIN_SERVER }}/cosign:signed"
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

