name: Docker Image Build, Sign, and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-sign-push-to-acr:
    runs-on: windows-latest

    env:  # Define environment variables
      REGISTRY: everestdemocontainerregistry.azurecr.io
      IMAGE_NAME: my-docker-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      run: |
        az login --use-device-code
        az acr login --name ${{ secrets.ACR_NAME }}
      shell: powershell

    - name: Build Docker image from Dockerfile
      run: |
        docker build -t my-docker-image .
      working-directory: .\  # Use the same directory containing your Dockerfile

    - name: cosign-installer
      uses: sigstore/cosign-installer@v3.1.2
      with:
        cosign-release: v2.2.0
        
    - name: Write signing key to disk
      run: 'echo "$KEY" > cosign.key'
      shell: bash
      env:
        KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        
    - name: Sign the published Docker image
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: cosign sign --key cosign.key everestdemocontainerregistry.azurecr.io/pa-submission-workflow-api:latest

    - name: Tag Docker image for ACR
      run: |
        docker tag pa-submission-workflow everestdemocontainerregistry.azurecr.io/pa-submission-workflow:latest
      working-directory: .

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push everestdemocontainerregistry.azurecr.io/pa-submission-workflow:latest
      shell: powershell
