name: Build, sign, and push container image

on:
  push:
    branches:
      - main

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "vamsi.sapireddy@outlook.com"
          git config --global user.name "vamsi560"
        env:
          CI: true

      - name: azure login
        run: |
          az login --use-device-code

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build the image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/cosign:abc6 .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/cosign:abc6
        env:
          DOCKER_CLI_ACR_LOGIN: 1  # Set this environment variable to use ACR credentials

      # Sign and push trust metadata for the image
      - name: Sign and push trust metadata
        run: |
          IMAGE_NAME="${{ secrets.ACR_LOGIN_SERVER }}/cosign:abc6"
          docker trust sign $IMAGE_NAME
        env:
          DOCKER_CLI_ACR_LOGIN: 1  # Set this environment variable to use ACR credentials
