name: Docker Image Build, Sign, and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-sign-push-to-acr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build Docker image
      run: |
        docker build -t my-docker-image .
      working-directory: ./  # Use the same directory containing your Dockerfile

    - name: cosign-installer
      uses: sigstore/cosign-installer@v3.1.2
      with:
        cosign-release: v2.2.0

    - name: Sign Docker image using Cosign
      run: |
        cosign sign --key cosign.key my-docker-image:latest
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Tag Docker image for ACR
      run: |
        docker tag my-docker-image ${{ secrets.ACR_REGISTRY }}/my-docker-image:latest
      working-directory: .

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.ACR_REGISTRY }}/my-docker-image:latest
