name: Build, sign, and push container image

on:
  push:
    branches:
      - main

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "vamsi.sapireddy@outlook.com"
          git config --global user.name "vamsi560"
        env:
          CI: true

      - name: azure login
        run: |
          az login --use-device-code

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build the image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/cosign:abc6 .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/cosign:abc6
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.2.0
        with:
          cosign-release: v2.2.0

      # Sign the image
      - name: Sign the image and get digest
        run: |
          SIGNED_IMAGE="cosign:abc6"
          cosign sign --key cosign.key --yes ${{ secrets.ACR_LOGIN_SERVER }}/$SIGNED_IMAGE
          cosign triangulate ${{ secrets.ACR_LOGIN_SERVER }}/$SIGNED_IMAGE
          cosign verify --key cosign.pub ${{ secrets.ACR_LOGIN_SERVER }}/$SIGNED_IMAGE
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          
      - name: Create a manifest with signature
        run: |
          # Generate a signature for the image and save it to a file
          cosign sign --signature=signature.txt ${{ secrets.ACR_LOGIN_SERVER }}/cosign:abc6

          # Create a new manifest that includes the image and the signature file
          docker manifest create cosign ${{ secrets.ACR_LOGIN_SERVER }}/cosign:signed ${{ secrets.ACR_LOGIN_SERVER }}/signature.txt

          # Annotate the manifest with the signature
          docker manifest annotate cosign cosign.io/signature=signature.txt

          # Push the manifest to the Docker registry
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/cosign:signed
        env:
          DOCKER_CLI_ACR_LOGIN: 1  
