name: Docker Image Sign and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-sign-push-to-acr:
    runs-on: ubuntu-latest

    env:
      REGISTRY: everestdemocontainerregistry.azurecr.io
      IMAGE_NAME: pa-submission-api
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login $REGISTRY -u ${{ secrets.ACR_USERNAME }} --password-stdin
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

    - name: Pull image from ACR
      run: |
        docker pull $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
      continue-on-error: true  # Continue even if the image is not found

    - name: cosign-installer
      uses: sigstore/cosign-installer@v2.2.0  
      with:
        cosign-release: v2.2.0  

    - name: Sign the pulled image
      run: |
        cosign sign -key cosign.key pa-submission-api:latest
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

    - name: Tag signed image for ACR
      run: |
        docker tag $REGISTRY/$IMAGE_NAME:$IMAGE_TAG $REGISTRY/$IMAGE_NAME:signed-$IMAGE_TAG
      continue-on-error: true  # Continue even if the image tagging fails

    - name: Push signed image to ACR
      run: |
        docker push $REGISTRY/$IMAGE_NAME:signed-$IMAGE_TAG
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
