name: Docker Image Build, Sign, and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-sign-push-to-acr:
    runs-on: windows-latest

    env:
      REGISTRY: everestdemocontainerregistry.azurecr.io
      IMAGE_NAME: my-docker-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image from Dockerfile
      run: |
        docker build -t my-docker-image .
      working-directory: .

    - name: Push Docker image to Azure Container Registry
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ env.REGISTRY }}
        docker push ${{ env.REGISTRY }}/my-docker-image:latest
      shell: bash
      working-directory: .

    - name: cosign-installer
      uses: sigstore/cosign-installer@v3.1.2
      with:
        cosign-release: v2.2.0

    - name: Write signing key to disk
      run: 'echo "$KEY" > cosign.key'
      shell: bash
      env:
        KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

    - name: Sign the published Docker image
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: cosign sign --key cosign.key ${{ env.REGISTRY }}/my-docker-image:latest

    - name: Tag Docker image for ACR
      run: |
        docker tag my-docker-image ${{ env.REGISTRY }}/my-docker-image:latest
      working-directory: .

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ env.REGISTRY }}/my-docker-image:latest
      shell: bash
