name: Docker Image Signing and Push

on:
  push:
    branches:
      - main 

jobs:
  build-and-sign:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        # Replace these with your Dockerfile path and tag
        docker build -t my-docker-image:latest .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push my-docker-image:latest
      shell: powershell

    - name: Install Cosign
      run: |
        Invoke-WebRequest -Uri https://github.com/sigstore/cosign/releases/latest/download/cosign-windows-amd64.exe -OutFile cosign.exe
        Move-Item -Path cosign.exe -Destination $env:USERPROFILE\bin\cosign.exe
        $env:Path += ";$env:USERPROFILE\bin"
      shell: powershell

    - name: Sign Docker image
      run: |
        cosign.exe sign -key <path-to-your-key> -a ${{ secrets.ACR_REGISTRY }}/<your-image>:latest my-docker-image:latest
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      shell: powershell
      working-directory: .\  # Change to the directory containing your Dockerfile

  push-to-acr:
    needs: build-and-sign
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az acr login --name ${{ secrets.ACR_NAME }}
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ACR_NAME: ${{ secrets.ACR_NAME }}

    - name: Pull and push Docker image
      run: |
        docker pull my-docker-image:latest
        docker tag my-docker-image:latest ${{ secrets.ACR_REGISTRY }}/<your-image>:latest
        docker push ${{ secrets.ACR_REGISTRY }}/<your-image>:latest
      shell: powershell
