name: Docker Image Build, Sign, and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-sign-push-to-acr:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      run: |
        az login --use-device-code
        az acr login --name ${{ secrets.ACR_NAME }}
      shell: powershell

    - name: Build Docker image from Dockerfile
      run: |
        docker build -t my-docker-image .
      working-directory: .\  # Use the same directory containing your Dockerfile
      
    - name: cosign-installer
      # You may pin to the exact commit or the version.
      # uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19
      uses: sigstore/cosign-installer@v3.1.2
      with:
        # cosign release version to be installed
        cosign-release: v2.2.0

    - name: Sign Docker image using Cosign
      run: |
        cosign.exe sign --key ${{ secrets.COSIGN_PRIVATE_KEY }} -a ${{ secrets.ACR_REGISTRY }}/my-docker-image:latest my-docker-image:latest
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      shell: powershell
      working-directory: .\  # Change to the directory containing your Dockerfile

    - name: Tag Docker image for ACR
      run: |
        docker tag my-docker-image ${{ secrets.ACR_REGISTRY }}/my-docker-image:latest
      working-directory: .

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.ACR_REGISTRY }}/my-docker-image:latest
      shell: powershell
